//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LADXHD_Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LADXHD_Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BBlurH_xnb {
            get {
                object obj = ResourceManager.GetObject("BBlurH.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BBlurV_xnb {
            get {
                object obj = ResourceManager.GetObject("BBlurV.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlurH_xnb {
            get {
                object obj = ResourceManager.GetObject("BlurH.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlurV_xnb {
            get {
                object obj = ResourceManager.GetObject("BlurV.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CircleShader_xnb {
            get {
                object obj = ResourceManager.GetObject("CircleShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ColorCloud_xnb {
            get {
                object obj = ResourceManager.GetObject("ColorCloud.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ColorShader_xnb {
            get {
                object obj = ResourceManager.GetObject("ColorShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] credits_font_xnb {
            get {
                object obj = ResourceManager.GetObject("credits font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] credits_header_font_xnb {
            get {
                object obj = ResourceManager.GetObject("credits header font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DamageShader_xnb {
            get {
                object obj = ResourceManager.GetObject("DamageShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dialog_eng_lng {
            get {
                object obj = ResourceManager.GetObject("dialog_eng.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dialog_esp_lng {
            get {
                object obj = ResourceManager.GetObject("dialog_esp.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dialog_ita_lng {
            get {
                object obj = ResourceManager.GetObject("dialog_ita.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dialog_por_lng {
            get {
                object obj = ResourceManager.GetObject("dialog_por.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dialog_rus_lng {
            get {
                object obj = ResourceManager.GetObject("dialog_rus.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamShrine01_map {
            get {
                object obj = ResourceManager.GetObject("dreamShrine01.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon2_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon2_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_3_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_3.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_4_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_4.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_2d_1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon6_2d_1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon6_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_map {
            get {
                object obj = ResourceManager.GetObject("dungeon6.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_3_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_3.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_4_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_4.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_5_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_5.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_6_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_6.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] editor_font_xnb {
            get {
                object obj = ResourceManager.GetObject("editor font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] editor_mono_font_xnb {
            get {
                object obj = ResourceManager.GetObject("editor mono font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] editor_small_mono_font_xnb {
            get {
                object obj = ResourceManager.GetObject("editor small mono font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EffectBlur_xnb {
            get {
                object obj = ResourceManager.GetObject("EffectBlur.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] egg_lower_floor_map {
            get {
                object obj = ResourceManager.GetObject("egg_lower_floor.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eng_lng {
            get {
                object obj = ResourceManager.GetObject("eng.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] esp_lng {
            get {
                object obj = ResourceManager.GetObject("esp.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FullShadowEffect_xnb {
            get {
                object obj = ResourceManager.GetObject("FullShadowEffect.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] headerFont_xnb {
            get {
                object obj = ResourceManager.GetObject("headerFont.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intro_atlas {
            get {
                object obj = ResourceManager.GetObject("intro.atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intro_png {
            get {
                object obj = ResourceManager.GetObject("intro.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ita_lng {
            get {
                object obj = ResourceManager.GetObject("ita.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap la {
            get {
                object obj = ResourceManager.GetObject("la", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LightFadeShader_xnb {
            get {
                object obj = ResourceManager.GetObject("LightFadeShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LightShader_xnb {
            get {
                object obj = ResourceManager.GetObject("LightShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Link_s_Awakening_DX_HD_exe {
            get {
                object obj = ResourceManager.GetObject("Link\'s Awakening DX HD.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] musicOverworld_data {
            get {
                object obj = ResourceManager.GetObject("musicOverworld.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] newHeaderFont_xnb {
            get {
                object obj = ResourceManager.GetObject("newHeaderFont.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] overworld_map {
            get {
                object obj = ResourceManager.GetObject("overworld.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] photos_png {
            get {
                object obj = ResourceManager.GetObject("photos.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] por_lng {
            get {
                object obj = ResourceManager.GetObject("por.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RoundedCorner_xnb {
            get {
                object obj = ResourceManager.GetObject("RoundedCorner.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RoundedCornerEffectBlur_xnb {
            get {
                object obj = ResourceManager.GetObject("RoundedCornerEffectBlur.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rus_lng {
            get {
                object obj = ResourceManager.GetObject("rus.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SaturationFilter_xnb {
            get {
                object obj = ResourceManager.GetObject("SaturationFilter.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] scripts_zScript {
            get {
                object obj = ResourceManager.GetObject("scripts.zScript", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShockEffect_xnb {
            get {
                object obj = ResourceManager.GetObject("ShockEffect.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] smallFont_xnb {
            get {
                object obj = ResourceManager.GetObject("smallFont.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ThanosShader_xnb {
            get {
                object obj = ResourceManager.GetObject("ThanosShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ui_atlas {
            get {
                object obj = ResourceManager.GetObject("ui.atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ui_png {
            get {
                object obj = ResourceManager.GetObject("ui.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WaleShader_xnb {
            get {
                object obj = ResourceManager.GetObject("WaleShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WobbleShader_xnb {
            get {
                object obj = ResourceManager.GetObject("WobbleShader.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xdelta3_exe {
            get {
                object obj = ResourceManager.GetObject("xdelta3.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
