//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LADXHD_Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LADXHD_Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] credits_font_xnb {
            get {
                object obj = ResourceManager.GetObject("credits font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] credits_header_font_xnb {
            get {
                object obj = ResourceManager.GetObject("credits header font.xnb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dialog_eng_lng {
            get {
                object obj = ResourceManager.GetObject("dialog_eng.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamShrine01_map {
            get {
                object obj = ResourceManager.GetObject("dreamShrine01.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dreamShrine01_map_data {
            get {
                object obj = ResourceManager.GetObject("dreamShrine01.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon1_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon1.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon2_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon2_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon2_2d_2_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon2_2d_2.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_1_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_1.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_2_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_2.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_3_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_3.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_3_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_3.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_4_map {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_4.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon5_2d_4_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon5_2d_4.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_2d_1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon6_2d_1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_2d_1_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon6_2d_1.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon6_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_2d_2_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon6_2d_2.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_map {
            get {
                object obj = ResourceManager.GetObject("dungeon6.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon6_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon6.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_1_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_1.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_1_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_1.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_2_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_2.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_2_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_2.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_3_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_3.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_3_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_3.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_4_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_4.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_4_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_4.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_5_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_5.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_5_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_5.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_6_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_6.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_2d_6_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8_2d_6.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_map {
            get {
                object obj = ResourceManager.GetObject("dungeon8.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon8_map_data {
            get {
                object obj = ResourceManager.GetObject("dungeon8.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] egg_lower_floor_map {
            get {
                object obj = ResourceManager.GetObject("egg_lower_floor.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] egg_lower_floor_map_data {
            get {
                object obj = ResourceManager.GetObject("egg_lower_floor.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eng_lng {
            get {
                object obj = ResourceManager.GetObject("eng.lng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intro_atlas {
            get {
                object obj = ResourceManager.GetObject("intro.atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] intro_png {
            get {
                object obj = ResourceManager.GetObject("intro.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap la {
            get {
                object obj = ResourceManager.GetObject("la", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Link_s_Awakening_DX_HD_exe {
            get {
                object obj = ResourceManager.GetObject("Link\'s Awakening DX HD.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] musicOverworld_data {
            get {
                object obj = ResourceManager.GetObject("musicOverworld.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] overworld_map {
            get {
                object obj = ResourceManager.GetObject("overworld.map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] overworld_map_data {
            get {
                object obj = ResourceManager.GetObject("overworld.map.data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] photos_png {
            get {
                object obj = ResourceManager.GetObject("photos.png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] scripts_zScript {
            get {
                object obj = ResourceManager.GetObject("scripts.zScript", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xdelta3_exe {
            get {
                object obj = ResourceManager.GetObject("xdelta3.exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xdelta3_patch {
            get {
                object obj = ResourceManager.GetObject("xdelta3 patch", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
